from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import numpy as np
import torch
from skimage.measure import marching_cubes

from .image_model import ImplicitImageToVoxelNet
from .mesh import field_to_obj


def _query_probabilities(
    model: ImplicitImageToVoxelNet,
    image_features: torch.Tensor,
    points: np.ndarray,
    device: torch.device,
    *,
    chunk_size: int = 65536,
) -> np.ndarray:
    results: list[np.ndarray] = []
    for start in range(0, len(points), chunk_size):
        tensor = torch.from_numpy(points[start : start + chunk_size]).to(
            device=device,
            dtype=torch.float32,
        )
        with torch.inference_mode(), torch.amp.autocast(
            "cuda",
            enabled=device.type == "cuda",
        ):
            logits = model.query_encoded(image_features, tensor.unsqueeze(0))
        results.append(torch.sigmoid(logits)[0].float().cpu().numpy())
    return np.concatenate(results) if results else np.empty(0, dtype=np.float32)


def _coarse_field(
    model: ImplicitImageToVoxelNet,
    image_features: torch.Tensor,
    device: torch.device,
    resolution: int,
    progress: Callable[[float], None] | None = None,
) -> np.ndarray:
    values = np.empty(resolution**3, dtype=np.float32)
    plane = resolution * resolution
    for start in range(0, len(values), 65536):
        stop = min(start + 65536, len(values))
        flat = np.arange(start, stop, dtype=np.int64)
        x = flat // plane
        remainder = flat % plane
        y = remainder // resolution
        z = remainder % resolution
        points = np.stack((x, y, z), axis=1).astype(np.float32)
        points = points / (resolution - 1) * 2.0 - 1.0
        values[start:stop] = _query_probabilities(
            model,
            image_features,
            points,
            device,
        )
        if progress is not None:
            progress(stop / len(values))
    return values.reshape((resolution, resolution, resolution))


def _active_cells(field: np.ndarray, threshold: float) -> np.ndarray:
    corners = (
        field[:-1, :-1, :-1],
        field[1:, :-1, :-1],
        field[:-1, 1:, :-1],
        field[:-1, :-1, 1:],
        field[1:, 1:, :-1],
        field[1:, :-1, 1:],
        field[:-1, 1:, 1:],
        field[1:, 1:, 1:],
    )
    minimum = np.minimum.reduce(corners)
    maximum = np.maximum.reduce(corners)
    return np.argwhere((minimum < threshold) & (maximum >= threshold))


def adaptive_implicit_to_obj(
    model: ImplicitImageToVoxelNet,
    image: torch.Tensor,
    path: str | Path,
    *,
    threshold: float,
    coarse_resolution: int = 128,
    progress: Callable[[float], None] | None = None,
) -> tuple[int, int, np.ndarray, bool]:
    if not 0.0 < threshold < 1.0:
        raise ValueError("threshold must be between 0 and 1")
    if coarse_resolution < 16 or coarse_resolution >= model.resolution:
        raise ValueError("coarse resolution must be below the output resolution")

    device = image.device
    model.eval()
    with torch.inference_mode(), torch.amp.autocast(
        "cuda",
        enabled=device.type == "cuda",
    ):
        image_features = model.encode_images(image)
    coarse = _coarse_field(
        model,
        image_features,
        device,
        coarse_resolution,
        progress=(
            (lambda value: progress(value * 0.3))
            if progress is not None
            else None
        ),
    )
    active = _active_cells(coarse, threshold)
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not len(active) or len(active) > 100_000:
        vertices, triangles = field_to_obj(
            coarse,
            destination,
            threshold=threshold,
        )
        if progress is not None:
            progress(1.0)
        return vertices, triangles, coarse, False

    final_resolution = model.resolution
    bounds = np.rint(
        np.linspace(0, final_resolution - 1, coarse_resolution)
    ).astype(np.int32)
    grouped: dict[tuple[int, int, int], list[np.ndarray]] = {}
    for cell in active:
        lengths = tuple(int(bounds[index + 1] - bounds[index] + 1) for index in cell)
        grouped.setdefault(lengths, []).append(cell)

    total_vertices = 0
    total_triangles = 0
    processed_cells = 0
    spacing = (2.0 / (final_resolution - 1),) * 3
    with destination.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("# Generated by tiny3dgen adaptive implicit marching cubes\n")
        for shape, cells in grouped.items():
            offsets = np.stack(
                np.meshgrid(
                    np.arange(shape[0], dtype=np.int32),
                    np.arange(shape[1], dtype=np.int32),
                    np.arange(shape[2], dtype=np.int32),
                    indexing="ij",
                ),
                axis=-1,
            ).reshape(-1, 3)
            cells_per_query = max(1, 131072 // len(offsets))
            for start in range(0, len(cells), cells_per_query):
                selected = np.asarray(cells[start : start + cells_per_query])
                origins = bounds[selected]
                grid_indices = origins[:, None, :] + offsets[None, :, :]
                points = grid_indices.reshape(-1, 3).astype(np.float32)
                points = points / (final_resolution - 1) * 2.0 - 1.0
                probabilities = _query_probabilities(
                    model,
                    image_features,
                    points,
                    device,
                ).reshape(len(selected), *shape)
                for origin, block in zip(origins, probabilities):
                    if float(block.min()) >= threshold or float(block.max()) < threshold:
                        continue
                    vertices, faces, _, _ = marching_cubes(
                        block,
                        level=threshold,
                        spacing=spacing,
                        allow_degenerate=False,
                    )
                    vertices += origin * spacing[0] - 1.0
                    for x, y, z in vertices:
                        handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
                    for a, b, c in faces + total_vertices + 1:
                        handle.write(f"f {a} {b} {c}\n")
                    total_vertices += len(vertices)
                    total_triangles += len(faces)
                processed_cells += len(selected)
                if progress is not None:
                    progress(0.3 + processed_cells / len(active) * 0.7)
    if total_triangles == 0:
        return (*field_to_obj(coarse, destination, threshold=threshold), coarse, False)
    return total_vertices, total_triangles, coarse, True
