from __future__ import annotations

from pathlib import Path

import numpy as np
from scipy.ndimage import gaussian_filter
from skimage.measure import marching_cubes


_FACES = (
    ((-1, 0, 0), ((0, 0, 0), (0, 0, 1), (0, 1, 1), (0, 1, 0))),
    ((1, 0, 0), ((1, 0, 0), (1, 1, 0), (1, 1, 1), (1, 0, 1))),
    ((0, -1, 0), ((0, 0, 0), (1, 0, 0), (1, 0, 1), (0, 0, 1))),
    ((0, 1, 0), ((0, 1, 0), (0, 1, 1), (1, 1, 1), (1, 1, 0))),
    ((0, 0, -1), ((0, 0, 0), (0, 1, 0), (1, 1, 0), (1, 0, 0))),
    ((0, 0, 1), ((0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1))),
)


def binarize_voxels(probabilities: np.ndarray, threshold: float) -> np.ndarray:
    voxels = probabilities >= threshold
    minimum_voxels = min(8, probabilities.size)
    if int(voxels.sum()) < minimum_voxels:
        cutoff = np.partition(probabilities.ravel(), -minimum_voxels)[-minimum_voxels]
        voxels = probabilities >= cutoff
    return voxels


def voxels_to_obj(voxels: np.ndarray, path: str | Path) -> tuple[int, int]:
    if voxels.ndim != 3 or len(set(voxels.shape)) != 1:
        raise ValueError("expected a cubic 3D voxel grid")

    occupied = voxels.astype(bool)
    resolution = occupied.shape[0]
    vertices: list[tuple[float, float, float]] = []
    triangles: list[tuple[int, int, int]] = []
    vertex_ids: dict[tuple[int, int, int], int] = {}

    def vertex_id(point: tuple[int, int, int]) -> int:
        if point not in vertex_ids:
            scale = 2.0 / resolution
            vertices.append(tuple((coordinate - resolution / 2) * scale for coordinate in point))
            vertex_ids[point] = len(vertices)
        return vertex_ids[point]

    for i, j, k in np.argwhere(occupied):
        for (di, dj, dk), corners in _FACES:
            neighbor = (i + di, j + dj, k + dk)
            inside = all(0 <= coordinate < resolution for coordinate in neighbor)
            if inside and occupied[neighbor]:
                continue
            face = [vertex_id((i + x, j + y, k + z)) for x, y, z in corners]
            triangles.append((face[0], face[1], face[2]))
            triangles.append((face[0], face[2], face[3]))

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("# Generated by tiny3dgen\n")
        for x, y, z in vertices:
            handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in triangles:
            handle.write(f"f {a} {b} {c}\n")
    return len(vertices), len(triangles)


def field_to_obj(
    probabilities: np.ndarray,
    path: str | Path,
    *,
    threshold: float,
    smoothing_sigma: float = 0.65,
) -> tuple[int, int]:
    if probabilities.ndim != 3 or len(set(probabilities.shape)) != 1:
        raise ValueError("expected a cubic 3D probability grid")
    if not 0.0 < threshold < 1.0:
        raise ValueError("threshold must be between 0 and 1")

    resolution = probabilities.shape[0]
    field = np.pad(
        probabilities.astype(np.float32, copy=False),
        1,
        mode="constant",
        constant_values=0.0,
    )
    if smoothing_sigma > 0:
        field = gaussian_filter(field, sigma=smoothing_sigma)
    if float(field.max()) <= threshold:
        return voxels_to_obj(binarize_voxels(probabilities, threshold), path)

    vertices, faces, _, _ = marching_cubes(
        field,
        level=threshold,
        allow_degenerate=False,
    )
    vertices -= 1.0
    vertices = (vertices + 0.5 - resolution / 2.0) * (2.0 / resolution)

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("# Generated by tiny3dgen marching cubes\n")
        for x, y, z in vertices:
            handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in faces + 1:
            handle.write(f"f {a} {b} {c}\n")
    return len(vertices), len(faces)
